# Generated by Django 5.1 on 2024-09-13 03:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import parler.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('schedule_delivery', models.BooleanField(default=False, verbose_name='Schedule Delivery')),
                ('fast_delivery', models.BooleanField(default=False, verbose_name='Fast Delivery')),
                ('own_delivery', models.BooleanField(default=False, verbose_name='Own Delivery')),
                ('delivery_company', models.BooleanField(default=False, verbose_name='Delivery Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('zone', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Zone')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ZoneTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'zone Translation',
                'db_table': 'branches_zone_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Branch')),
                ('serial_number', models.CharField(max_length=15, verbose_name='Serial Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('license', models.CharField(max_length=100, verbose_name='License')),
                ('license_file', models.FileField(upload_to='licenses', verbose_name='License File')),
                ('commercial_register', models.CharField(max_length=100, verbose_name='Commercial Register')),
                ('commercial_register_file', models.FileField(upload_to='commercial_registers', verbose_name='Commercial Register')),
                ('tax_number', models.CharField(max_length=100, verbose_name='Tax Number')),
                ('tax_file', models.FileField(upload_to='tax_files', verbose_name='Tax File')),
                ('iban', models.CharField(max_length=100, verbose_name='IBAN')),
                ('iban_number', models.CharField(max_length=100, verbose_name='IBAN Number')),
                ('iban_file', models.FileField(upload_to='iban_files', verbose_name='IBAN File')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
