# Generated by Django 5.1 on 2024-09-13 03:03

import parler.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('level', models.CharField(choices=[('ALL', 'All Branches'), ('ASSIGNED_BRANCHES', 'Assigned Branches'), ('OWNER', 'Owner Branches')], default='OWNER', max_length=20, verbose_name='Permission Level')),
                ('view', models.BooleanField(default=False, verbose_name='Can view model')),
                ('edit', models.BooleanField(default=False, verbose_name='Can edit model')),
                ('delete', models.BooleanField(default=False, verbose_name='Can delete model')),
                ('create', models.BooleanField(default=False, verbose_name='Can create model')),
                ('object_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Object')),
                ('view_fields', models.JSONField(blank=True, null=True, verbose_name='Who are fields can view ? ')),
                ('edit_fields', models.JSONField(blank=True, null=True, verbose_name='Who are fields can edit ? ')),
                ('create_fields', models.JSONField(blank=True, null=True, verbose_name='Who are fields can create ? ')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('level', models.CharField(choices=[('ALL', 'All'), ('ASSIGNED_BRANCHES', 'Assigned Branch'), ('OWNER', 'Owner')], db_index=True, default='OWNER', max_length=20, verbose_name='Role Level')),
                ('codename', models.SlugField(unique=True, verbose_name='Code name')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RoleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Role Translation',
                'db_table': 'permissions_role_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssignedBranches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('branches', models.ManyToManyField(related_name='admins', to='branches.branch', verbose_name='Branches')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
